
// https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

enum TcpUdp {
  TCP = 'tcp',
  UDP = 'udp',
};

enum DangerLevel {
  LOW = 'low',
  MIDDLE = 'middle',
  HIGH = 'high',
};

type Port = {
  port: number;
  service: string;
  description: string;
  description_ja: string;
  danger_level: DangerLevel;
  protocol: TcpUdp[];
  system_port: boolean;
};

const ports: Port[] = [
  {
    port: 1,
    service: 'tcpmux',
    description: 'TCP Port Service Multiplexer',
    description_ja: 'TCPポートサービスマルチプレクサ',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 5,
    service: 'rje',
    description: 'Remote Job Entry',
    description_ja: 'リモートジョブエントリ',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 7,
    service: 'echo',
    description: 'Echo',
    description_ja: 'エコー',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 9,
    service: 'discard',
    description: 'Discard',
    description_ja: 'ディスカード',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 11,
    service: 'systat',
    description: 'Active Users',
    description_ja: 'アクティブユーザー',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 13,
    service: 'daytime',
    description: 'Daytime',
    description_ja: 'デイタイム',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 17,
    service: 'qotd',
    description: 'Quote of the Day',
    description_ja: '今日の名言',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 18,
    service: 'msp',
    description: 'Message Send Protocol',
    description_ja: 'メッセージ送信プロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 19,
    service: 'chargen',
    description: 'Character Generator',
    description_ja: '文字ジェネレータ',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 20,
    service: 'ftp-data',
    description: 'File Transfer [Default Data]',
    description_ja: 'ファイル転送 [デフォルトデータ]',
    danger_level: DangerLevel.MIDDLE,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 21,
    service: 'ftp',
    description: 'File Transfer [Control]',
    description_ja: 'ファイル転送 [コントロール]',
    danger_level: DangerLevel.MIDDLE,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 22,
    service: 'ssh',
    description: 'Secure Shell',
    description_ja: 'セキュアシェル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 23,
    service: 'telnet',
    description: 'Telnet',
    description_ja: 'テルネット',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 25,
    service: 'smtp',
    description: 'Simple Mail Transfer',
    description_ja: 'シンプルメール転送',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 37,
    service: 'time',
    description: 'Time',
    description_ja: 'タイム',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 42,
    service: 'nameserver',
    description: 'Host Name Server',
    description_ja: 'ホスト名サーバー',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 43,
    service: 'nicname',
    description: 'Who Is',
    description_ja: 'Whois',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 49,
    service: 'tacacs',
    description: 'Login Host Protocol (TACACS)',
    description_ja: 'ログインホストプロトコル (TACACS)',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 53,
    service: 'domain',
    description: 'Domain Name Server',
    description_ja: 'ドメイン名サーバー',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 70,
    service: 'gopher',
    description: 'Gopher',
    description_ja: 'ゴーファー',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 79,
    service: 'finger',
    description: 'Finger',
    description_ja: 'フィンガー',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 80,
    service: 'http',
    description: 'Hypertext Transfer Protocol',
    description_ja: 'ハイパーテキスト転送プロトコル',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 103,
    service: 'xns-time',
    description: 'XNS Time Protocol',
    description_ja: 'XNSタイムプロトコル',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 108,
    service: 'sccopmce',
    description: 'SCCP',
    description_ja: 'SCCP',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 109,
    service: 'pop2',
    description: 'Post Office Protocol - Version 2',
    description_ja: 'ポストオフィスプロトコル - バージョン2',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 110,
    service: 'pop3',
    description: 'Post Office Protocol - Version 3',
    description_ja: 'ポストオフィスプロトコル - バージョン3',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 111,
    service: 'sunrpc',
    description: 'SUN Remote Procedure Call',
    description_ja: 'SUNリモートプロシージャコール',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 113,
    service: 'auth',
    description: 'Authentication Service',
    description_ja: '認証サービス',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 115,
    service: 'sftp',
    description: 'Simple File Transfer Protocol',
    description_ja: 'シンプルファイル転送プロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 117,
    service: 'uucp-path',
    description: 'UUCP Path Service',
    description_ja: 'UUCPパスサービス',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 119,
    service: 'nntp',
    description: 'Network News Transfer Protocol',
    description_ja: 'ネットワークニュース転送プロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 123,
    service: 'ntp',
    description: 'Network Time Protocol',
    description_ja: 'ネットワークタイムプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 135,
    service: 'epmap',
    description: 'DCE endpoint resolution',
    description_ja: 'DCEエンドポイント解決',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 137,
    service: 'netbios-ns',
    description: 'NetBIOS Name Service',
    description_ja: 'NetBIOS名前サービス',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 138,
    service: 'netbios-dgm',
    description: 'NetBIOS Datagram Service',
    description_ja: 'NetBIOSデータグラムサービス',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 139,
    service: 'netbios-ssn',
    description: 'NetBIOS Session Service',
    description_ja: 'NetBIOSセッションサービス',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 143,
    service: 'imap',
    description: 'Internet Message Access Protocol',
    description_ja: 'インターネットメッセージアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 161,
    service: 'snmp',
    description: 'Simple Network Management Protocol',
    description_ja: 'シンプルネットワークマネジメントプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 162,
    service: 'snmptrap',
    description: 'Simple Network Management Protocol Trap',
    description_ja: 'シンプルネットワークマネジメントプロトコルトラップ',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 177,
    service: 'xdmcp',
    description: 'X Display Manager Control Protocol',
    description_ja: 'Xディスプレイマネージャコントロールプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 179,
    service: 'bgp',
    description: 'Border Gateway Protocol',
    description_ja: 'ボーダーゲートウェイプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP, TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 389,
    service: 'ldap',
    description: 'Lightweight Directory Access Protocol',
    description_ja: '軽量ディレクトリアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 427,
    service: 'svrloc',
    description: 'Service Location Protocol',
    description_ja: 'サービスロケーションプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 443,
    service: 'https',
    description: 'HTTP over TLS/SSL',
    description_ja: 'TLS/SSLを使用したHTTP',
    danger_level: DangerLevel.LOW,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 445,
    service: 'microsoft-ds',
    description: 'Microsoft-DS Active Directory',
    description_ja: 'Microsoft-DSアクティブディレクトリ',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 464,
    service: 'kpasswd',
    description: 'Kerberos password change',
    description_ja: 'Kerberosパスワード変更',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 500,
    service: 'isakmp',
    description: 'Internet Security Association and Key Management Protocol',
    description_ja: 'インターネットセキュリティアソシエーションとキーマネジメントプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 514,
    service: 'syslog',
    description: 'System Logging',
    description_ja: 'システムログ',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 520,
    service: 'rip',
    description: 'Routing Information Protocol',
    description_ja: 'ルーティング情報プロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.UDP],
    system_port: true,
  },
  {
    port: 593,
    service: 'http-rpc-epmap',
    description: 'HTTP RPC Endpoint Mapper',
    description_ja: 'HTTP RPCエンドポイントマッパー',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 636,
    service: 'ldaps',
    description: 'Lightweight Directory Access Protocol over TLS/SSL',
    description_ja: 'TLS/SSLを使用した軽量ディレクトリアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 989,
    service: 'ftps-data',
    description: 'FTP over TLS/SSL (data)',
    description_ja: 'TLS/SSLを使用したFTP（データ）',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 990,
    service: 'ftps',
    description: 'FTP over TLS/SSL (control)',
    description_ja: 'TLS/SSLを使用したFTP（コントロール）',
    danger_level: DangerLevel.MIDDLE,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 992,
    service: 'telnets',
    description: 'Telnet over TLS/SSL',
    description_ja: 'TLS/SSLを使用したTelnet',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 993,
    service: 'imaps',
    description: 'Internet Message Access Protocol over TLS/SSL',
    description_ja: 'TLS/SSLを使用したインターネットメッセージアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 995,
    service: 'pop3s',
    description: 'Post Office Protocol version 3 over TLS/SSL',
    description_ja: 'TLS/SSLを使用したPost Office Protocol version 3',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
  {
    port: 3268,
    service: 'ldap',
    description: 'Lightweight Directory Access Protocol',
    description_ja: '軽量ディレクトリアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: false,
  },
  {
    port: 3269,
    service: 'ldaps',
    description: 'Lightweight Directory Access Protocol over TLS/SSL',
    description_ja: 'TLS/SSLを使用した軽量ディレクトリアクセスプロトコル',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: false,
  },
  {
    port: 3306,
    service: 'mysql',
    description: 'MySQL',
    description_ja: 'MySQL',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: false,
  },
  {
    port: 3389,
    service: 'ms-wbt-server',
    description: 'Microsoft Terminal Services',
    description_ja: 'Microsoft Terminal Services',
    danger_level: DangerLevel.HIGH,
    protocol: [TcpUdp.TCP],
    system_port: true,
  },
];

export default ports;
export type { Port };
export { DangerLevel };
