// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/debug/ping/": {
            "get": {
                "description": "テスト用APIの詳細",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DebugResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "テスト用APIの詳細",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DebugResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "テスト用APIの詳細",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DebugResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "テスト用APIの詳細",
                "consumes": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DebugResponse"
                        }
                    }
                }
            }
        },
        "/api/lookup-host": {
            "get": {
                "description": "ホスト検索用のAPI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ドメイン名",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.LookupHostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.LookupHostResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.LookupHostResponse"
                        }
                    }
                }
            }
        },
        "/api/name-resolver": {
            "get": {
                "description": "名前解決用のAPI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ドメイン名",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.NameResolverResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.NameResolverResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.NameResolverResponse"
                        }
                    }
                }
            }
        },
        "/api/port-scan": {
            "get": {
                "description": "ポートスキャン用のAPI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ホスト名",
                        "name": "host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "開始ポート番号",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "終了ポート番号",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "スキャン時間(秒) | 1-60(default: 5)",
                        "name": "waittime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.PortscanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.PortscanResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.PortscanResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.DebugResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                }
            }
        },
        "app.LookupHostResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "domain": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "app.NameResolverResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "app.PortscanResponse": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "open": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "to": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
